services:
  otel-collector-service:
    image: local/otel-collector-service:latest
    container_name: otel-collector-service
    hostname: docker-local
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55678:55678"
      - "55679:55679"
    networks:
      - develop-network
    environment:
      - EXPORTER=otlp_http/new_relic
      - NEWRELIC_ENDPOINT=https://otlp.nr-data.net
      - NEWRELIC_APIKEY=b8808def9ddc8a94cad3d450c5c78299FFFFNRAL

networks:
  develop-network:
    external: true
    name: develop