services:
  otel-collector-service:
    image: local/otel-collector-service:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55678:55678"
      - "55679:55679"
    networks:
      - develop-network
    env_file:
      - local.env
    healthcheck:
      test: ["CMD", "/otelcol-contrib", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  develop-network:
    external: true
    name: develop