receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  filter/health_endpoint:
    traces:
      span:
        - attributes["http.route"] == "/admin/health"
  resource/drop_unneeded_resource_attributes:
    attributes:
      - key: host.arch
        action: delete
      - key: os.description
        action: delete
      - key: os.type
        action: delete
      - key: os.version
        action: delete
      - key: process.command_args
        action: delete
      - key: process.command_line
        action: delete
      - key: process.executable.path
        action: delete
      - key: process.pid
        action: delete
      - key: process.runtime.description
        action: delete
      - key: process.runtime.name
        action: delete
      - key: aws.ecs.cluster.arn
        action: delete
      - key: aws.ecs.container.arn
        action: delete
      - key: aws.ecs.container.image.id
        action: delete
      - key: aws.ecs.task.arn
        action: delete
      - key: aws.log.group.arns
        action: delete
      - key: aws.log.group.names
        action: delete
      - key: aws.log.stream.arns
        action: delete
      - key: aws.log.stream.names
        action: delete
      - key: cloud.resource_id
        action: delete

exporters:
  debug:
    verbosity: detailed
  otlp_http/new_relic:
    endpoint: ${env:NEWRELIC_ENDPOINT:-default_endpoint}
    headers:
      api-key: ${env:NEWRELIC_APIKEY:-default_apikey}

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
        - filter/health_endpoint
        - resource/drop_unneeded_resource_attributes
      exporters:
        - ${env:EXPORTER:-debug}
    metrics:
      receivers:
        - otlp
      processors:
        - batch
        - resource/drop_unneeded_resource_attributes
      exporters:
        - ${env:EXPORTER:-debug}
    logs:
      receivers:
        - otlp
      processors:
        - batch
        - resource/drop_unneeded_resource_attributes
      exporters:
        - ${env:EXPORTER:-debug}