services:
  influxdb3-core:
    image: influxdb:3-core
    user: root
    ports:
      - '8181:8181'
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb3-core-data:/var/lib/influxdb3/data
      - influxdb3-core-data:/var/lib/influxdb3/plugins
    restart: unless-stopped
    networks:
      - develop-network
#influxdb3 create token --admin
#Token: apiv3_R87ShFdegjh_xFi8d1o57FN-kDS7r0WVAqz_jleqRi4zFeliXBZNqT8ILSno3H6qfvLXeMvU-bKuGYCQQFTsSQ

  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    ports:
      - "8888:8080"
    networks:
      - develop-network
    volumes:
      - ./config:/app-root/config:ro
      - influxdb3-explorer-data:/db
      - ./ssl:/etc/nginx/ssl:ro
      - ./ca-certs:/ca-certs:ro
      - ./admin-instructions:/app-root/admin-instructions:ro
    restart: unless-stopped
    command: [ "--mode=admin" ]

networks:
  develop-network:
    external: true
    name: develop

volumes:
  influxdb3-core-data:
    name: influxdb3-core-data
  influxdb3-explorer-data:
    name: influxdb3-explorer-data