services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    hostname: docker-local
    user: root
    ports:
      - '8181:8181'
    command:
      - influxdb3
      - serve
      - --node-id=docker-local-node
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb-data:/var/lib/influxdb3/data
      - influxdb-data:/var/lib/influxdb3/plugins
    restart: unless-stopped
    networks:
      - develop-network
#Token: apiv3_hjhSehgKdbeUrRKOHpQzrFegAvsqAH5m-TSpW7OVXuoBwNC0pRSjWZZWsEuPg-lWNRY6coybqVl2bVDA8s2yvg

  influxdb-ui:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb-ui
    hostname: docker-local
    ports:
      - "8888:8080"
    networks:
      - develop-network
    volumes:
      - influxdb-ui-data:/db
      - ./config:/app-root/config:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./ca-certs:/ca-certs:ro
    restart: unless-stopped
    command: [ "--mode=admin" ]
    environment:
      - DEFAULT_INFLUX_SERVER=http://influxdb:8181
      - DEFAULT_INFLUX_DATABASE=services
      - DEFAULT_API_TOKEN=apiv3_hjhSehgKdbeUrRKOHpQzrFegAvsqAH5m-TSpW7OVXuoBwNC0pRSjWZZWsEuPg-lWNRY6coybqVl2bVDA8s2yvg
      - DEFAULT_SERVER_NAME=local

networks:
  develop-network:
    external: true
    name: develop

volumes:
  influxdb-data:
    name: influxdb-data
  influxdb-ui-data:
    name: influxdb-ui-data