name: Push otel-collector-service on updating main branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - .github/workflows/otel-collector-service-prod.yml
      - otel-collector-service/configs/*.yaml
      - otel-collector-service/Dockerfile
      - otel-collector-service/version.yaml

env:
  REGISTRY: davidgandalcio
  REPOSITORY: otel-collector-service
  AWS_REGION: us-east-1
  ECS_CLUSTER: homeproject-services-prod-ecs-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Get otel collector version
        id: lookupOtelCollectorVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq '.otel-collector-contrib.version' 'otel-collector-service/version.yaml'

      - name: docker login
        run: |
          docker login -u $REGISTRY -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push the Docker image
        id: push-image
        run: |
          bash otel-collector-service/docker_build.sh prod ${{ steps.lookupOtelCollectorVersion.outputs.result }}

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download javalin-template task definition
        run: |
          aws ecs describe-task-definition --task-definition javalin-template-prod --query taskDefinition > javalin-template-task-definition.json

      - name: Fill in the new image ID in the javalin-template task definition
        id: task-def-javalin-template
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: javalin-template-task-definition.json
          container-name: ${{ env.REPOSITORY }}
          image: ${{ steps.push-image.outputs.image }}

      - name: Deploy javalin-template task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-javalin-template.outputs.task-definition }}
          service: javalin-template
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false

      - name: Download planner-service task definition
        run: |
          aws ecs describe-task-definition --task-definition planner-service-prod --query taskDefinition > planner-service-task-definition.json

      - name: Fill in the new image ID in the planner-service task definition
        id: task-def-planner-service
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: planner-service-task-definition.json
          container-name: ${{ env.REPOSITORY }}
          image: ${{ steps.push-image.outputs.image }}

      - name: Deploy planner-service task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-planner-service.outputs.task-definition }}
          service: planner-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false

      - name: Download games-service task definition
        run: |
          aws ecs describe-task-definition --task-definition games-service-prod --query taskDefinition > games-service-task-definition.json

      - name: Fill in the new image ID in the games-service task definition
        id: task-def-games-service
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: games-service-task-definition.json
          container-name: ${{ env.REPOSITORY }}
          image: ${{ steps.push-image.outputs.image }}

      - name: Deploy games-service task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-games-service.outputs.task-definition }}
          service: games-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false